# Generated by Django 5.2 on 2025-04-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Volunteering',
        ),
    ]
