# Generated by Django 5.2 on 2025-04-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('specialization', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
