# Generated by Django 5.2 on 2025-04-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_language_skill_volunteering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
    ]
