# Generated by Django 5.2 on 2025-04-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_youtubeintro_youtubevideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
