# Generated by Django 5.2 on 2025-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('nt_code', models.CharField(max_length=100)),
                ('best_bro_name', models.CharField(max_length=100)),
            ],
        ),
    ]
