# Generated by Django 5.2 on 2025-04-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_savedmessage_starredmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedMessage',
        ),
    ]
