# Generated by Django 5.2 on 2025-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_certificate_education_experience_language_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portodata',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
